#!/usr/bin/env python3
"""
Script to compare assembly output generated by `cargo asm` for `asmview`
between the current working directory and a specified Git revision (default: main).
"""

import argparse
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path


def get_workspace_root() -> Path:
    cmd = ["git", "rev-parse", "--show-toplevel"]
    res = subprocess.run(cmd, capture_output=True, text=True, check=True)
    return Path(res.stdout.strip())


def list_asmview_functions(cwd: Path) -> list[str]:
    cmd = ["cargo", "asm", "-p", "asmview", "--lib"]
    res = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    
    # Example output:
    # Try one of those by name or a sequence number
    # 0 "<ph::phast::compressed_array::SuxEliasFano as ph::phast::compressed_array::CompressedArray>::get" [367]
    # 1 "core::hash::Hasher::write_u64" [343]
    # 2 "phast_get_f2_seed_only" [852]
    # 3 "phast_get_f2_shift_only_wrapped_1" [838]
    # 4 "phast_get_f_seed_only" [605]
    
    functions = []
    pattern = re.compile(r'^\d+\s+"([^"]+)"')
    for line in res.stderr.splitlines():
        match = pattern.search(line.strip())
        if match:
            fn_name = match.group(1)
            # Filter out external/dependency functions if desired, or keep extern "C" functions
            functions.append(fn_name)
    
    # If no stderr output or failed to parse, fall back to parsing lib.rs extern "C" fn names
    if not functions:
        lib_rs = cwd / "internal" / "asmview" / "src" / "lib.rs"
        if lib_rs.exists():
            fn_pattern = re.compile(r'pub\s+extern\s+"C"\s+fn\s+([a_zA-Z0-9_]+)')
            functions = fn_pattern.findall(lib_rs.read_text())
            
    return functions


def get_function_asm(cwd: Path, fn_name: str) -> str:
    cmd = ["cargo", "asm", "-p", "asmview", "--lib", fn_name]
    res = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if res.returncode != 0:
        print(f"Warning: Failed to get asm for function '{fn_name}': {res.stderr}", file=sys.stderr)
        return ""
    return res.stdout


def get_all_asm(cwd: Path, target_functions: list[str] | None = None) -> str:
    all_functions = list_asmview_functions(cwd)
    if target_functions:
        all_functions = [f for f in all_functions if any(t in f for t in target_functions)]
    
    out = []
    for fn in sorted(all_functions):
        out.append(f"=== FUNCTION: {fn} ===")
        asm = get_function_asm(cwd, fn)
        out.append(asm)
        out.append("\n")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(
        description="Compare assembly generated by cargo asm between current working tree and a git revision."
    )
    parser.add_argument(
        "ref",
        nargs="?",
        default="main",
        help="Git revision to compare against (default: main)",
    )
    parser.add_argument(
        "-f",
        "--function",
        action="append",
        help="Specific function(s) to compare (can be specified multiple times). Default: all functions in asmview",
    )
    
    args = parser.parse_args()
    workspace_root = get_workspace_root()
    
    print(f"Generating assembly for CURRENT working directory...")
    current_asm = get_all_asm(workspace_root, args.function)
    
    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_path = Path(tmp_dir)
        current_asm_file = tmp_path / "current.asm"
        ref_asm_file = tmp_path / f"{args.ref.replace('/', '_')}.asm"
        worktree_dir = tmp_path / "worktree"
        
        current_asm_file.write_text(current_asm)
        
        print(f"Creating temporary git worktree for revision '{args.ref}'...")
        cmd_worktree = ["git", "worktree", "add", "--detach", str(worktree_dir), args.ref]
        res_wt = subprocess.run(cmd_worktree, cwd=workspace_root, capture_output=True, text=True)
        if res_wt.returncode != 0:
            print(f"Error creating git worktree for ref '{args.ref}':\n{res_wt.stderr}", file=sys.stderr)
            sys.exit(1)
            
        try:
            print(f"Generating assembly for Git revision '{args.ref}'...")
            ref_asm = get_all_asm(worktree_dir, args.function)
            ref_asm_file.write_text(ref_asm)
            
            print("\n" + "=" * 80)
            print(f"DIFF: {args.ref} (left) vs CURRENT (right)")
            print("=" * 80 + "\n")
            
            diff_cmd = ["git", "diff", "--no-index", "--color=always", str(ref_asm_file), str(current_asm_file)]
            diff_res = subprocess.run(diff_cmd, capture_output=True, text=True)
            
            if diff_res.returncode == 0:
                print("No assembly differences found!")
            else:
                print(diff_res.stdout)
                
        finally:
            print("Cleaning up temporary git worktree...")
            subprocess.run(["git", "worktree", "remove", "--force", str(worktree_dir)], cwd=workspace_root, capture_output=True)


if __name__ == "__main__":
    main()
