[workspace]
members = ["ph", "csf", "minimum_redundancy", "dyn_size_of", "fsum", "bitm", "binout", "mphf_benchmark", "csf_benchmark"]
resolver = "2"

[patch.crates-io]
dyn_size_of = { version=">=0.1", path="dyn_size_of" }

[profile.release]
lto = true
codegen-units = 1
