[package]
name = "cseq_benchmark"
version = "0.0.2"
authors = ["Piotr Beling <piotr.beling@wmii.uni.lodz.pl>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "The program for benchmarking compact sequences"
documentation = "https://docs.rs/cseq_benchmark"
repository = "https://github.com/beling/bsuccinct-rs"
readme = "README.md"
include = [ "**/*.rs", "Cargo.toml", "README.md" ]
categories = [ "data-structures", "algorithms", "compression", "science" ]
keywords = [ "compression", "sequence", "succinct", "elias-fano", "benchmark" ]

[dependencies]
cseq = { version ="0.1", path = "../cseq" }
clap = { version="4", features = ["derive"] }
dyn_size_of = { version="0.4", path="../dyn_size_of" }
cpu-time = "1"
bitm = { version="0.3", path="../bitm" }